#!/usr/bin/env python3
from __future__ import annotations

import pathlib


ROOT = pathlib.Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"
OUTPUT_PATH = ROOT / "config" / "cliproxyapi-config.yaml"
AUTH_DIR = ROOT / "data" / "cliproxyapi" / "auths"


def load_env(path: pathlib.Path) -> dict[str, str]:
    env: dict[str, str] = {}
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in raw_line:
            continue
        key, value = raw_line.split("=", 1)
        env[key.strip()] = value.strip()
    return env


def yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


env = load_env(ENV_PATH)
port = env.get("CLIPROXY_PORT", "8317").strip() or "8317"
host = env.get("CLIPROXY_LISTEN_HOST", "127.0.0.1").strip() or "127.0.0.1"
api_key = env.get("CLIPROXY_API_KEY", "").strip()
management_key = env.get("CLIPROXY_MANAGEMENT_KEY", "").strip()

if not api_key:
    raise SystemExit("CLIPROXY_API_KEY must be set in .env before rendering CLIProxyAPI config")

AUTH_DIR.mkdir(parents=True, exist_ok=True)

lines = [
    "# Generated by scripts/render-cliproxy-config.py from .env",
    f"host: {yaml_quote(host)}",
    f"port: {port}",
    "tls:",
    "  enable: false",
    '  cert: ""',
    '  key: ""',
    "remote-management:",
    "  allow-remote: false",
    f"  secret-key: {yaml_quote(management_key)}",
    f"  disable-control-panel: {'false' if management_key else 'true'}",
    f"auth-dir: {yaml_quote(str(AUTH_DIR))}",
    "api-keys:",
    f"  - {yaml_quote(api_key)}",
    "debug: false",
    "logging-to-file: false",
    "usage-statistics-enabled: true",
    "request-retry: 3",
    "routing:",
    '  strategy: "round-robin"',
]

OUTPUT_PATH.write_text("\n".join(lines) + "\n")
print(f"Rendered {OUTPUT_PATH}")
print(f"Auth dir: {AUTH_DIR}")
