#!/usr/bin/env python3
from __future__ import annotations

import pathlib
import re


ROOT = pathlib.Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"
OUTPUT_PATH = ROOT / "config" / "litellm-config.yaml"


def load_env(path: pathlib.Path) -> dict[str, str]:
    env: dict[str, str] = {}
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in raw_line:
            continue
        key, value = raw_line.split("=", 1)
        parsed_value = value.strip()
        if len(parsed_value) >= 2 and parsed_value[0] == parsed_value[-1] and parsed_value[0] in {"'", '"'}:
            parsed_value = parsed_value[1:-1]
        env[key.strip()] = parsed_value
    return env


def openai_sort_key(name: str) -> tuple[int, int, str]:
    if name == "OPENAI_API_KEY":
        return (1, 0, name)
    match = re.fullmatch(r"OPENAI_API_KEY_(\d+)", name)
    if match is None:
        return (10**9, 0, name)
    return (int(match.group(1)), 1, name)


def is_enabled(raw: str) -> bool:
    value = raw.strip().lower()
    return value not in {"0", "false", "no", "off"}


env = load_env(ENV_PATH)

openai_var_names = sorted(
    [
        key
        for key in env
        if key == "OPENAI_API_KEY" or re.fullmatch(r"OPENAI_API_KEY_\d+", key)
    ],
    key=openai_sort_key,
)

active_openai_vars: list[str] = []
seen_openai_values: set[str] = set()
for name in openai_var_names:
    value = env.get(name, "")
    if not value:
        continue
    if value in seen_openai_values:
        continue
    seen_openai_values.add(value)
    active_openai_vars.append(name)

anthropic_enabled = bool(env.get("ANTHROPIC_API_KEY", "").strip())
minimax_enabled = bool(env.get("MINIMAX_API_KEY", "").strip())
danglamgiau_api_key = env.get("DANGLAMGIAU_API_KEY", "").strip()
danglamgiau_api_base = env.get("DANGLAMGIAU_API_BASE", "").strip()
danglamgiau_user_agent = (
    env.get(
        "DANGLAMGIAU_USER_AGENT",
        (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/134.0.0.0 Safari/537.36"
        ),
    ).strip()
)
danglamgiau_enabled = bool(danglamgiau_api_key and danglamgiau_api_base) and is_enabled(
    env.get("DANGLAMGIAU_ENABLE", "0")
)
danglamgiau_model_prefix = (
    env.get("DANGLAMGIAU_MODEL_PREFIX", "dlg").strip() or "dlg"
)
danglamgiau_models: list[str] = []
for raw_model in env.get(
    "DANGLAMGIAU_MODELS", "gpt-5,gpt-5-codex"
).split(","):
    model = raw_model.strip()
    if model and model not in danglamgiau_models:
        danglamgiau_models.append(model)
claudible_api_key = env.get("CLAUDIBLE_API_KEY", "").strip()
claudible_api_base = env.get("CLAUDIBLE_API_BASE", "").strip()
claudible_user_agent = (
    env.get(
        "CLAUDIBLE_USER_AGENT",
        (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/134.0.0.0 Safari/537.36"
        ),
    ).strip()
)
claudible_enabled = bool(claudible_api_key and claudible_api_base) and is_enabled(
    env.get("CLAUDIBLE_ENABLE", "0")
)
claudible_model_prefix = (
    env.get("CLAUDIBLE_MODEL_PREFIX", "claudible").strip() or "claudible"
)
claudible_models: list[str] = []
for raw_model in env.get(
    "CLAUDIBLE_MODELS", "claude-sonnet-4.6,claude-opus-4.6,claude-haiku-4.5"
).split(","):
    model = raw_model.strip()
    if model and model not in claudible_models:
        claudible_models.append(model)
cliproxy_api_key = env.get("CLIPROXY_API_KEY", "").strip()
cliproxy_api_base = env.get("CLIPROXY_API_BASE", "").strip()
cliproxy_enabled = bool(cliproxy_api_key and cliproxy_api_base) and is_enabled(
    env.get("CLIPROXY_ENABLE", "1")
)
cliproxy_model_prefix = (
    env.get("CLIPROXY_MODEL_PREFIX", "codex-oauth").strip() or "codex-oauth"
)
cliproxy_models: list[str] = []
for raw_model in env.get(
    "CLIPROXY_MODELS", "gpt-5.4,gpt-5.3-codex"
).split(","):
    model = raw_model.strip()
    if model and model not in cliproxy_models:
        cliproxy_models.append(model)
has_real_provider_keys = (
    anthropic_enabled
    or bool(active_openai_vars)
    or minimax_enabled
    or danglamgiau_enabled
    or claudible_enabled
    or cliproxy_enabled
)

lines: list[str] = [
    "# Generated by scripts/render-litellm-config.py from .env",
]

if active_openai_vars:
    lines.append("# Active OpenAI key env vars: " + ", ".join(active_openai_vars))
if len(active_openai_vars) > 1:
    lines.append(
        "# LiteLLM will load-balance across repeated openai-gpt-5-4 deployments."
    )
if danglamgiau_enabled:
    lines.append(
        "# DangLamGiau marketplace enabled; LiteLLM will expose dlg-* aliases backed by https://danglamgiau.com/v1."
    )
if claudible_enabled:
    lines.append(
        "# Claudible enabled; LiteLLM will expose claudible-* aliases backed by https://claudible.io/v1."
    )
if cliproxy_enabled:
    lines.append(
        "# CLIProxyAPI OAuth bridge enabled; LiteLLM will expose codex-oauth-* aliases."
    )
if not has_real_provider_keys:
    lines.append(
        "# No non-empty provider keys found yet; keeping placeholder deployments so initial boot stays compatible."
    )

lines.append("model_list:")

if anthropic_enabled or not has_real_provider_keys:
    lines.extend(
        [
            "  - model_name: claude-opus-4-6",
            "    litellm_params:",
            "      model: anthropic/claude-opus-4-6",
            "      api_key: os.environ/ANTHROPIC_API_KEY",
            "",
        ]
    )

if active_openai_vars:
    for name in active_openai_vars:
        lines.extend(
            [
                "  - model_name: openai-gpt-5-4",
                "    litellm_params:",
                "      model: openai/gpt-5.4",
                f"      api_key: os.environ/{name}",
                "",
            ]
        )
else:
    lines.extend(
        [
            "  - model_name: openai-gpt-5-4",
            "    litellm_params:",
            "      model: openai/gpt-5.4",
            "      api_key: os.environ/OPENAI_API_KEY",
            "",
        ]
    )

if minimax_enabled:
    lines.extend(
        [
            "  - model_name: MiniMax-M2.5",
            "    litellm_params:",
            "      model: minimax/MiniMax-M2.5",
            "      api_key: os.environ/MINIMAX_API_KEY",
            "      api_base: os.environ/MINIMAX_API_BASE",
            "",
            "  - model_name: MiniMax-M2.1",
            "    litellm_params:",
            "      model: minimax/MiniMax-M2.1",
            "      api_key: os.environ/MINIMAX_API_KEY",
            "      api_base: os.environ/MINIMAX_API_BASE",
            "",
        ]
    )

if danglamgiau_enabled:
    for upstream_model in danglamgiau_models:
        alias_suffix = upstream_model.replace("/", "-").replace(".", "-")
        lines.extend(
            [
                f"  - model_name: {danglamgiau_model_prefix}-{alias_suffix}",
                "    litellm_params:",
                f"      model: openai/{upstream_model}",
                "      api_base: os.environ/DANGLAMGIAU_API_BASE",
                "      api_key: os.environ/DANGLAMGIAU_API_KEY",
                "      extra_headers:",
                f'        User-Agent: "{danglamgiau_user_agent}"',
                "",
            ]
        )

if claudible_enabled:
    for upstream_model in claudible_models:
        alias_suffix = upstream_model.replace("/", "-").replace(".", "-")
        lines.extend(
            [
                f"  - model_name: {claudible_model_prefix}-{alias_suffix}",
                "    litellm_params:",
                f"      model: openai/{upstream_model}",
                "      api_base: os.environ/CLAUDIBLE_API_BASE",
                "      api_key: os.environ/CLAUDIBLE_API_KEY",
                "      extra_headers:",
                f'        User-Agent: "{claudible_user_agent}"',
                "",
            ]
        )

if cliproxy_enabled:
    for upstream_model in cliproxy_models:
        alias_suffix = upstream_model.replace("/", "-").replace(".", "-")
        alias_names = [f"{cliproxy_model_prefix}-{alias_suffix}"]
        if upstream_model in {"gpt-5.4", "gpt-5.3-codex"}:
            alias_names.insert(0, upstream_model)

        for alias_name in alias_names:
            lines.extend(
                [
                    f"  - model_name: {alias_name}",
                    "    litellm_params:",
                    f"      model: openai/{upstream_model}",
                    "      api_base: os.environ/CLIPROXY_API_BASE",
                    "      api_key: os.environ/CLIPROXY_API_KEY",
                    "",
                ]
            )

lines.extend(
    [
        "general_settings:",
        "  # Store auth + spend in Postgres; set keys via container env.",
        "  master_key: os.environ/LITELLM_MASTER_KEY",
        "  database_url: os.environ/DATABASE_URL",
        "",
        "router_settings:",
        "  routing_strategy: simple-shuffle",
        "  num_retries: 3",
        "  retry_policy:",
        '    AuthenticationErrorRetries: 3',
        '    RateLimitErrorRetries: 3',
        '    TimeoutErrorRetries: 3',
        '    InternalServerErrorRetries: 3',
        "",
        "litellm_settings:",
        "  drop_params: true",
        "  set_verbose: false",
        "  json_logs: true",
    ]
)

OUTPUT_PATH.write_text("\n".join(lines) + "\n")

print(f"Rendered {OUTPUT_PATH}")
if active_openai_vars:
    print(f"OpenAI deployments: {len(active_openai_vars)}")
else:
    print("OpenAI deployments: placeholder via OPENAI_API_KEY")
print(f"Anthropic enabled: {'yes' if anthropic_enabled else 'no'}")
print(f"DangLamGiau enabled: {'yes' if danglamgiau_enabled else 'no'}")
print(f"Claudible enabled: {'yes' if claudible_enabled else 'no'}")
print(f"CLIProxyAPI enabled: {'yes' if cliproxy_enabled else 'no'}")
