#!/usr/bin/env python3
from __future__ import annotations

import pathlib
import re


ROOT = pathlib.Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"
OUTPUT_PATH = ROOT / "config" / "litellm-config.yaml"


def load_env(path: pathlib.Path) -> dict[str, str]:
    env: dict[str, str] = {}
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in raw_line:
            continue
        key, value = raw_line.split("=", 1)
        env[key.strip()] = value.strip()
    return env


def openai_sort_key(name: str) -> tuple[int, int, str]:
    if name == "OPENAI_API_KEY":
        return (1, 0, name)
    match = re.fullmatch(r"OPENAI_API_KEY_(\d+)", name)
    if match is None:
        return (10**9, 0, name)
    return (int(match.group(1)), 1, name)


env = load_env(ENV_PATH)

openai_var_names = sorted(
    [
        key
        for key in env
        if key == "OPENAI_API_KEY" or re.fullmatch(r"OPENAI_API_KEY_\d+", key)
    ],
    key=openai_sort_key,
)

active_openai_vars: list[str] = []
seen_openai_values: set[str] = set()
for name in openai_var_names:
    value = env.get(name, "")
    if not value:
        continue
    if value in seen_openai_values:
        continue
    seen_openai_values.add(value)
    active_openai_vars.append(name)

anthropic_enabled = bool(env.get("ANTHROPIC_API_KEY", "").strip())
minimax_enabled = bool(env.get("MINIMAX_API_KEY", "").strip())
has_real_provider_keys = anthropic_enabled or bool(active_openai_vars) or minimax_enabled

lines: list[str] = [
    "# Generated by scripts/render-litellm-config.py from .env",
]

if active_openai_vars:
    lines.append("# Active OpenAI key env vars: " + ", ".join(active_openai_vars))
if len(active_openai_vars) > 1:
    lines.append(
        "# LiteLLM will load-balance across repeated gpt-5.1-codex deployments."
    )
if not has_real_provider_keys:
    lines.append(
        "# No non-empty provider keys found yet; keeping placeholder deployments so initial boot stays compatible."
    )

lines.append("model_list:")

if anthropic_enabled or not has_real_provider_keys:
    lines.extend(
        [
            "  - model_name: claude-opus-4-6",
            "    litellm_params:",
            "      model: anthropic/claude-opus-4-6",
            "      api_key: os.environ/ANTHROPIC_API_KEY",
            "",
        ]
    )

if active_openai_vars:
    for name in active_openai_vars:
        lines.extend(
            [
                "  - model_name: gpt-5.1-codex",
                "    litellm_params:",
                "      model: openai/gpt-5.1-codex",
                f"      api_key: os.environ/{name}",
                "",
            ]
        )
else:
    lines.extend(
        [
            "  - model_name: gpt-5.1-codex",
            "    litellm_params:",
            "      model: openai/gpt-5.1-codex",
            "      api_key: os.environ/OPENAI_API_KEY",
            "",
        ]
    )

if minimax_enabled:
    lines.extend(
        [
            "  - model_name: MiniMax-M2.5",
            "    litellm_params:",
            "      model: minimax/MiniMax-M2.5",
            "      api_key: os.environ/MINIMAX_API_KEY",
            "      api_base: os.environ/MINIMAX_API_BASE",
            "",
            "  - model_name: MiniMax-M2.1",
            "    litellm_params:",
            "      model: minimax/MiniMax-M2.1",
            "      api_key: os.environ/MINIMAX_API_KEY",
            "      api_base: os.environ/MINIMAX_API_BASE",
            "",
        ]
    )

lines.extend(
    [
        "general_settings:",
        "  # Store auth + spend in Postgres; set keys via container env.",
        "  master_key: os.environ/LITELLM_MASTER_KEY",
        "  database_url: os.environ/DATABASE_URL",
        "",
        "router_settings:",
        "  routing_strategy: simple-shuffle",
        "  num_retries: 3",
        "  retry_policy:",
        '    AuthenticationErrorRetries: 3',
        '    RateLimitErrorRetries: 3',
        '    TimeoutErrorRetries: 3',
        '    InternalServerErrorRetries: 3',
        "",
        "litellm_settings:",
        "  drop_params: true",
        "  set_verbose: false",
        "  json_logs: true",
    ]
)

OUTPUT_PATH.write_text("\n".join(lines) + "\n")

print(f"Rendered {OUTPUT_PATH}")
if active_openai_vars:
    print(f"OpenAI deployments: {len(active_openai_vars)}")
else:
    print("OpenAI deployments: placeholder via OPENAI_API_KEY")
print(f"Anthropic enabled: {'yes' if anthropic_enabled else 'no'}")
